### ISSUE TITLE
Add form validation on the Create a Joke form

### ISSUE THREAD

**Issue by Utkarshrajmishra** [remarkablegames/just-jokes#304]
## Problem
The 'Create Joke' dialog form does not have any validation. If the 'noun' and 'punchline' fields are left blank and the 'Create Joke' button is clicked, a joke is being created without a noun and punchline.

![Screenshot from 2024-09-20 23-03-21](https://github.com/user-attachments/assets/060d75e0-328f-437c-b0bf-e3c801f5dd10)
![Screenshot from 2024-09-20 23-11-44](https://github.com/user-attachments/assets/d791aee7-2a2b-48da-b833-4326c422eefc)

## Suggested Solution
Form validation should be added to the 'Create Joke' form so that if any of the fields are left blank, an error message is shown.

**Comment by remarkablemark** [comment]
Thanks @Utkarshrajmishra, I will take a look at this later today.
